version: '3.8'
services:
  php:
    build:
      context: .  # Diretório atual, já que o Dockerfile está no mesmo local
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html  # Alterado para copiar do diretório ./src (não ./backend/src)
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
    volumes:
      - task_manager_data:/var/lib/mysql

volumes:
  task_manager_data:
